/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type Team = {
  _id: string
  _type: 'team'
  _createdAt: string
  _updatedAt: string
  _rev: string
  order?: number
  name?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  role?: string
  leadership?: boolean
}

export type TranslationMetadata = {
  _id: string
  _type: 'translation.metadata'
  _createdAt: string
  _updatedAt: string
  _rev: string
  translations?: Array<
    {
      _key: string
    } & InternationalizedArrayReferenceValue
  >
  schemaTypes?: Array<string>
}

export type InternationalizedArrayReferenceValue = {
  _type: 'internationalizedArrayReferenceValue'
  value?:
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'homePage'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'aboutPage'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'testimonialsPage'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'webinarPage'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'navigation'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'consultationPage'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'faq'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'caseStudy'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'testimonial'
      }
}

export type Testimonial = {
  _id: string
  _type: 'testimonial'
  _createdAt: string
  _updatedAt: string
  _rev: string
  clientName?: string
  comment?: string
  date?: string
}

export type CaseStudy = {
  _id: string
  _type: 'caseStudy'
  _createdAt: string
  _updatedAt: string
  _rev: string
  clientName?: string
  videoUrl?: string
  thumbnail?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Faq = {
  _id: string
  _type: 'faq'
  _createdAt: string
  _updatedAt: string
  _rev: string
  question?: string
  answer?: string
}

export type ConsultationPage = {
  _id: string
  _type: 'consultationPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  subtitle?: string
  offerInformation?: {
    label?: string
    items?: Array<{
      icon?: string
      title?: string
      _key: string
    }>
  }
  closerInformation?: {
    title?: string
    subtitle?: string
  }
  publishedAt?: string
}

export type Navigation = {
  _id: string
  _type: 'navigation'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  items?: Array<{
    name?: string
    href?: string
    hideOnHomePage?: boolean
    hidden?: boolean
    children?: Array<{
      name?: string
      href?: string
      hidden?: boolean
      _key: string
    }>
    _key: string
  }>
  bookCall?: {
    title?: string
    href?: string
    hidden?: boolean
  }
}

export type WebinarPage = {
  _id: string
  _type: 'webinarPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  subtitle?: string
  CTA?: {
    label?: string
    url?: string
  }
  webinarInformationSection?: {
    date?: string
    timezone?: string
  }
  benefitsSection?: {
    title?: string
    benefits?: Array<{
      title?: string
      description?: string
      _key: string
    }>
    CTA?: {
      label?: string
      url?: string
    }
  }
  aboutHostSection?: {
    title?: string
    subTitle?: string
    paragraph1?: string
    paragraph2?: string
  }
  statisticsSection?: Array<{
    prefix?: string
    number?: number
    postfix?: string
    description?: string
    _key: string
  }>
  registrationSection?: {
    form?: {
      title?: string
      firstName?: string
      lastName?: string
      email?: string
      phone?: string
      submitButton?: string
    }
    webinarFeatures?: Array<{
      icon?: string
      title?: string
      _key: string
    }>
  }
  publishedAt?: string
}

export type TestimonialsPage = {
  _id: string
  _type: 'testimonialsPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  title?: string
  description?: string
  CTA?: {
    label?: string
    url?: string
  }
  publishedAt?: string
}

export type AboutPage = {
  _id: string
  _type: 'aboutPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  subtitle?: string
  missionVisionSection?: {
    mission?: {
      title?: string
      content?: string
    }
    vision?: {
      title?: string
      content?: string
    }
    CTA?: {
      label?: string
      url?: string
    }
  }
  aboutRabihSection?: {
    title?: string
    subTitle?: string
    paragraph1?: string
    paragraph2?: string
    cta?: {
      label?: string
      url?: string
    }
  }
  testimonialsSection?: {
    title?: string
    CTA?: {
      label?: string
      url?: string
    }
  }
  gallerySection?: {
    title?: string
    description?: string
  }
  callToActionSection?: {
    title?: string
    description?: string
    CTA?: {
      label?: string
      url?: string
    }
  }
  publishedAt?: string
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  subtitle?: string
  buttons?: Array<{
    label?: string
    url?: string
    _key: string
  }>
  whyUsSection?: {
    title?: string
    description?: string
    reasons?: Array<{
      title?: string
      description?: string
      _key: string
    }>
  }
  aboutSection?: {
    title?: string
    description?: string
    paragraphs?: Array<string>
    CTA?: {
      label?: string
      url?: string
    }
  }
  testimonialsSection?: {
    title?: string
    CTA?: {
      label?: string
      url?: string
    }
  }
  partnersSection?: {
    title?: string
  }
  consultationProcessSection?: {
    title?: string
    description?: string
    steps?: Array<{
      icon?: string
      title?: string
      subtitle?: string
      description?: string
      _key: string
    }>
    CTA?: {
      label?: string
      url?: string
    }
  }
  whyCyprusSection?: {
    title?: string
    reasons?: Array<{
      title?: string
      description?: string
      _key: string
    }>
    CTA?: {
      label?: string
      url?: string
    }
  }
  caseStudiesSection?: {
    title?: string
    description?: string
  }
  investorCommunitySection?: {
    CTA?: {
      label?: string
      url?: string
    }
  }
  meetRabihSection?: {
    title?: string
    subTitle?: string
    paragraph1?: string
    paragraph2?: string
    CTA?: {
      label?: string
      url?: string
    }
  }
  leadershipTeamSection?: {
    title?: string
    description?: string
  }
  callToActionSection?: {
    title?: string
    description?: string
    CTA?: {
      label?: string
      url?: string
    }
  }
  freebieSignupSection?: {
    title?: string
    description?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    consent?: string
    form?: {
      firstName?: string
      lastName?: string
      email?: string
      submit?: string
    }
  }
  publishedAt?: string
}

export type InternationalizedArrayReference = Array<
  {
    _key: string
  } & InternationalizedArrayReferenceValue
>

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityFileAsset
  | Geopoint
  | Slug
  | Team
  | TranslationMetadata
  | InternationalizedArrayReferenceValue
  | Testimonial
  | CaseStudy
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata
  | Faq
  | ConsultationPage
  | Navigation
  | WebinarPage
  | TestimonialsPage
  | AboutPage
  | HomePage
  | InternationalizedArrayReference
export declare const internalGroqTypeReferenceTo: unique symbol
