/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Footer = {
  _id: string
  _type: 'footer'
  _createdAt: string
  _updatedAt: string
  _rev: string
  copyright?: string
  socialMedia?: {
    facebook?: string
    twitter?: string
    instagram?: string
    youtube?: string
  }
  contactSection?: {
    phone?: {
      phoneNumber?: string
      phoneLink?: string
    }
    email?: {
      email?: string
      emailLink?: string
    }
    address?: {
      fullAddress?: string
      googleMapsLink?: string
      mapsEmbedLink?: string
    }
  }
}

export type Testimonial = {
  _id: string
  _type: 'testimonial'
  _createdAt: string
  _updatedAt: string
  _rev: string
  clientName?: string
  type?: 'client' | 'webinar-attendee'
  clientImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  comment?: string
  date?: string
}

export type PropertyFeature = {
  _id: string
  _type: 'propertyFeature'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  type?: 'external' | 'internal'
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  description?: string
}

export type PropertyKind = {
  _id: string
  _type: 'propertyKind'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  main?: boolean
  images?: Array<
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
        }
        media?: unknown
        _type: 'file'
        _key: string
      }
  >
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type Property = {
  _id: string
  _type: 'property'
  _createdAt: string
  _updatedAt: string
  _rev: string
  basicInfo?: {
    title?: string
    slug?: Slug
    price?: {
      currency?: 'GBP' | 'USD' | 'EUR' | 'AED' | 'TRY'
      amount?: number
    }
    images?: Array<{
      image?: {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
      }
      isCover?: boolean
      alt?: string
      _key: string
    }>
    status?: 'draft' | 'published' | 'archived' | 'sold' | 'rented' | 'on-hold'
    type?: Array<{
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'propertyKind'
    }>
    featured?: boolean
    location?: 'famagusta' | 'girne' | 'lefkosa' | 'guzelyurt' | 'iskele' | 'lefke' | 'meneou'
    listingType?: 'sale' | 'rent'
    saleType?: 'off-plan' | 'resale'
    bedrooms?: number
    livingRooms?: number
    bathrooms?: number
  }
  features?: {
    external?: Array<{
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'propertyFeature'
    }>
    internal?: Array<{
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'propertyFeature'
    }>
  }
  agent?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'propertyAgent'
  }
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  details?: {
    area?: {
      size?: number
      unit?: 'm2' | 'sqft' | 'sqkm' | 'sqmi'
    }
    yearBuilt?: number
    titleDeed?: 'exchange' | 'english' | 'turkish' | 'cyprus'
    floors?: number
    floorLevel?: number
    availableForTrade?: boolean
    gatedCommunity?: boolean
    management?: boolean
    residential?: boolean
    furnished?: boolean
    availableForViewing?: boolean
  }
}

export type PropertyAgent = {
  _id: string
  _type: 'propertyAgent'
  _createdAt: string
  _updatedAt: string
  _rev: string
  code?: string
  firstName?: string
  lastName?: string
  email?: string
  phone?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type BlogPostTag = {
  _id: string
  _type: 'blogPostTag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
}

export type TranslationMetadata = {
  _id: string
  _type: 'translation.metadata'
  _createdAt: string
  _updatedAt: string
  _rev: string
  translations?: Array<
    {
      _key: string
    } & InternationalizedArrayReferenceValue
  >
  schemaTypes?: Array<string>
}

export type InternationalizedArrayReferenceValue = {
  _type: 'internationalizedArrayReferenceValue'
  value?:
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'homePage'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'aboutPage'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'testimonialsPage'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'webinarPage'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'navigation'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'consultationPage'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'bankPackagesPage'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'blogPage'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'waitlistPage'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'faq'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'caseStudy'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'blogPost'
      }
}

export type BlogPost = {
  _id: string
  _type: 'blogPost'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  description?: string
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  readTime?: number
  author?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'team'
  }
  category?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'blogPostCategory'
  }
  tags?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'blogPostTag'
  }>
  faqs?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'faq'
  }>
  published?: boolean
  publishedAt?: string
  seo?: SeoMetaFields
  language?: string
}

export type BlogPostCategory = {
  _id: string
  _type: 'blogPostCategory'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
}

export type Team = {
  _id: string
  _type: 'team'
  _createdAt: string
  _updatedAt: string
  _rev: string
  order?: number
  name?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  role?: string
  leadership?: boolean
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type CaseStudy = {
  _id: string
  _type: 'caseStudy'
  _createdAt: string
  _updatedAt: string
  _rev: string
  clientName?: string
  videoUrl?: string
  thumbnail?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Faq = {
  _id: string
  _type: 'faq'
  _createdAt: string
  _updatedAt: string
  _rev: string
  question?: string
  answer?: string
  language?: string
}

export type WaitlistPage = {
  _id: string
  _type: 'waitlistPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  seo?: SeoMetaFields
  title?: string
  subtitle?: string
  waitlistForm?: {
    form?: {
      title?: string
      firstName?: string
      lastName?: string
      email?: string
      phone?: string
      submitButton?: string
    }
  }
  publishedAt?: string
  language?: string
}

export type BlogPage = {
  _id: string
  _type: 'blogPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  subtitle?: string
  featuredPosts?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'blogPost'
  }>
  seo?: SeoMetaFields
  language?: string
}

export type BankPackagesPage = {
  _id: string
  _type: 'bankPackagesPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  seo?: SeoMetaFields
  title?: string
  subtitle?: string
  packages?: Array<{
    title?: string
    icon?: string
    subtitle?: string
    slug?: string
    stripePriceId?: string
    minimumDeposit?: number
    buttonText?: string
    moreText?: string
    description?: string
    price?: number
    features?: Array<{
      title?: string
      _key: string
    }>
    _key: string
  }>
  form?: {
    title?: string
    personalInformationSection?: {
      title?: string
      salutation?: string
      firstName?: string
      lastName?: string
      email?: string
      phone?: string
    }
    additionalInformationSection?: {
      title?: string
      dateOfBirth?: string
      placeOfBirth?: string
      address?: string
      city?: string
      country?: string
      zipCode?: string
      maritalStatus?: string
      profession?: string
    }
    parentsInformationSection?: {
      title?: string
      fathersFirstName?: string
      fathersLastName?: string
      mothersFirstName?: string
      mothersLastName?: string
      mothersMaidenName?: string
    }
    bankAndLawyerSection?: {
      title?: string
      bankAppointment?: string
      initialDeposit?: string
      amountToBeTransferred?: string
      lawyerAppointment?: string
      travelDetails?: {
        title?: string
        areYouTravellingAlone?: string
        numberOfPeople?: string
        whoIsTravellingWithYou?: string
        numberOfChildren?: string
        comments?: string
        doYouNeed?: string
        arrivalDate?: string
        departureDate?: string
        hotel?: string
        requireRentalCar?: string
        carSize?: string
      }
      additionalServices?: {
        title?: string
        airportTransfer?: string
      }
    }
    documentUploadsSection?: {
      title?: string
      mainTravellerDocuments?: {
        title?: string
        passport?: string
        utilityBill?: string
        idFront?: string
        idBack?: string
        proofOfTravel?: string
      }
      additionalTravellerDocuments?: {
        title?: string
        additionalTravellerRadios?: {
          title?: string
          passport?: string
          id?: string
        }
        passport?: string
        idFront?: string
        idBack?: string
        proofOfTravel?: string
      }
    }
    buttons?: {
      back?: string
      next?: string
      submit?: string
    }
  }
  publishedAt?: string
  language?: string
}

export type ConsultationPage = {
  _id: string
  _type: 'consultationPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  seo?: SeoMetaFields
  title?: string
  subtitle?: string
  offerInformation?: {
    label?: string
    items?: Array<{
      icon?: string
      title?: string
      _key: string
    }>
  }
  closerInformation?: {
    title?: string
    subtitle?: string
  }
  publishedAt?: string
  language?: string
}

export type Navigation = {
  _id: string
  _type: 'navigation'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  items?: Array<{
    name?: string
    href?: string
    hideOnHomePage?: boolean
    hidden?: boolean
    children?: Array<{
      name?: string
      href?: string
      hidden?: boolean
      _key: string
    }>
    _key: string
  }>
  bookCall?: {
    title?: string
    href?: string
    hidden?: boolean
  }
  language?: string
}

export type WebinarPage = {
  _id: string
  _type: 'webinarPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  seo?: SeoMetaFields
  title?: string
  subtitle?: string
  CTA?: {
    label?: string
    url?: string
  }
  webinarInformationSection?: {
    date?: string
    timezone?: string
  }
  benefitsSection?: {
    title?: string
    benefits?: Array<{
      title?: string
      description?: string
      _key: string
    }>
    CTA?: {
      label?: string
      url?: string
    }
  }
  aboutHostSection?: {
    title?: string
    subTitle?: string
    paragraph1?: string
    paragraph2?: string
  }
  statisticsSection?: Array<{
    prefix?: string
    number?: number
    postfix?: string
    description?: string
    _key: string
  }>
  registrationSection?: {
    form?: {
      title?: string
      firstName?: string
      lastName?: string
      email?: string
      phone?: string
      submitButton?: string
    }
    webinarFeatures?: Array<{
      icon?: string
      title?: string
      _key: string
    }>
  }
  publishedAt?: string
  language?: string
}

export type TestimonialsPage = {
  _id: string
  _type: 'testimonialsPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  seo?: SeoMetaFields
  name?: string
  title?: string
  description?: string
  CTA?: {
    label?: string
    url?: string
  }
  publishedAt?: string
  language?: string
}

export type AboutPage = {
  _id: string
  _type: 'aboutPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  seo?: SeoMetaFields
  title?: string
  subtitle?: string
  missionVisionSection?: {
    mission?: {
      title?: string
      content?: string
    }
    vision?: {
      title?: string
      content?: string
    }
    CTA?: {
      label?: string
      url?: string
    }
  }
  aboutRabihSection?: {
    title?: string
    subTitle?: string
    paragraph1?: string
    paragraph2?: string
    cta?: {
      label?: string
      url?: string
    }
  }
  testimonialsSection?: {
    title?: string
    CTA?: {
      label?: string
      url?: string
    }
  }
  gallerySection?: {
    title?: string
    description?: string
  }
  callToActionSection?: {
    title?: string
    description?: string
    CTA?: {
      label?: string
      url?: string
    }
  }
  publishedAt?: string
  language?: string
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  seo?: SeoMetaFields
  title?: string
  subtitle?: string
  buttons?: Array<{
    label?: string
    url?: string
    _key: string
  }>
  whyUsSection?: {
    title?: string
    description?: string
    reasons?: Array<{
      title?: string
      description?: string
      _key: string
    }>
  }
  aboutSection?: {
    title?: string
    description?: string
    paragraphs?: Array<string>
    CTA?: {
      label?: string
      url?: string
    }
  }
  testimonialsSection?: {
    title?: string
    CTA?: {
      label?: string
      url?: string
    }
  }
  partnersSection?: {
    title?: string
  }
  consultationProcessSection?: {
    title?: string
    description?: string
    steps?: Array<{
      icon?: string
      title?: string
      subtitle?: string
      description?: string
      _key: string
    }>
    CTA?: {
      label?: string
      url?: string
    }
  }
  whyCyprusSection?: {
    title?: string
    reasons?: Array<{
      title?: string
      description?: string
      _key: string
    }>
    CTA?: {
      label?: string
      url?: string
    }
  }
  caseStudiesSection?: {
    title?: string
    description?: string
  }
  investorCommunitySection?: {
    CTA?: {
      label?: string
      url?: string
    }
  }
  meetRabihSection?: {
    title?: string
    subTitle?: string
    paragraph1?: string
    paragraph2?: string
    CTA?: {
      label?: string
      url?: string
    }
  }
  leadershipTeamSection?: {
    title?: string
    description?: string
  }
  callToActionSection?: {
    title?: string
    description?: string
    CTA?: {
      label?: string
      url?: string
    }
  }
  freebieSignupSection?: {
    title?: string
    description?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    consent?: string
    form?: {
      firstName?: string
      lastName?: string
      email?: string
      submit?: string
    }
  }
  publishedAt?: string
  language?: string
}

export type InternationalizedArrayReference = Array<
  {
    _key: string
  } & InternationalizedArrayReferenceValue
>

export type MetaTag = {
  _type: 'metaTag'
  metaAttributes?: Array<
    {
      _key: string
    } & MetaAttribute
  >
}

export type MetaAttribute = {
  _type: 'metaAttribute'
  attributeKey?: string
  attributeType?: 'string' | 'image'
  attributeValueImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  attributeValueString?: string
}

export type SeoMetaFields = {
  _type: 'seoMetaFields'
  nofollowAttributes?: boolean
  metaTitle?: string
  metaDescription?: string
  metaImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  seoKeywords?: Array<string>
  openGraph?: OpenGraph
  additionalMetaTags?: Array<
    {
      _key: string
    } & MetaTag
  >
  twitter?: Twitter
}

export type Twitter = {
  _type: 'twitter'
  cardType?: string
  creator?: string
  site?: string
  handle?: string
}

export type OpenGraph = {
  _type: 'openGraph'
  url?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  title?: string
  description?: string
  siteName?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | Geopoint
  | Footer
  | Testimonial
  | PropertyFeature
  | PropertyKind
  | SanityFileAsset
  | Property
  | PropertyAgent
  | BlogPostTag
  | TranslationMetadata
  | InternationalizedArrayReferenceValue
  | BlogPost
  | BlogPostCategory
  | Team
  | Slug
  | CaseStudy
  | Faq
  | WaitlistPage
  | BlogPage
  | BankPackagesPage
  | ConsultationPage
  | Navigation
  | WebinarPage
  | TestimonialsPage
  | AboutPage
  | HomePage
  | InternationalizedArrayReference
  | MetaTag
  | MetaAttribute
  | SeoMetaFields
  | Twitter
  | OpenGraph
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata
export declare const internalGroqTypeReferenceTo: unique symbol
