/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type TextWithImage = {
  _type: 'textWithImage'
  heading?: string
  body?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'image'
  }
  imagePosition?: 'left' | 'right'
  verticalAlign?: 'start' | 'center' | 'end'
  gap?: 'sm' | 'md' | 'lg'
  imageSize?: '4-6' | '5-5' | '6-4'
  imageRounded?: boolean
}

export type Table = {
  _type: 'table'
  caption?: string
  columns?: Array<{
    title?: string
    align?: 'left' | 'center' | 'right'
    width?: number
    _key: string
  }>
  rows?: Array<{
    cells?: Array<{
      text?: string
      _key: string
    }>
    _key: string
  }>
  options?: {
    headerTone?: 'brand' | 'neutral'
    inverseHeaderText?: boolean
    borders?: 'rows' | 'grid' | 'none'
    dense?: boolean
    mobileStack?: boolean
  }
}

export type Spacer = {
  _type: 'spacer'
  preset?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'custom'
  customHeight?: number
}

export type Subheading = {
  _type: 'subheading'
  label?: string
  align?: 'left' | 'center' | 'right'
  variant?: 'solid' | 'subtle' | 'outline'
  tone?: 'brand' | 'neutral' | 'accent' | 'info' | 'success' | 'warning' | 'danger'
  size?: 'sm' | 'md' | 'lg'
  uppercase?: boolean
}

export type HeadingWithImage = {
  _type: 'headingWithImage'
  heading?: string
  headingLevel?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'
  subheading?: string
  backgroundImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  height?: 'sm' | 'md' | 'lg' | 'full'
  align?: 'left' | 'center' | 'right'
  textTone?: 'light' | 'dark'
  overlayOpacity?: number
  imageOpacity?: number
}

export type Gallery = {
  _type: 'gallery'
  title?: string
  images?: Array<{
    image?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    caption?: string
    alt?: string
    _key: string
  }>
  layout?: 'grid' | 'masonry' | 'carousel' | 'lightbox'
  columns?: number
  showCaptions?: boolean
  enableLightbox?: boolean
}

export type Audio = {
  _type: 'audio'
  file?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
    }
    media?: unknown
    _type: 'file'
  }
  title?: string
  artist?: string
  description?: string
  duration?: number
  showPlayer?: boolean
  autoplay?: boolean
  loop?: boolean
  showDownloadButton?: boolean
  coverImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Quote = {
  _type: 'quote'
  text?: string
  author?: string
  source?: string
  url?: string
  style?: 'default' | 'large' | 'pull' | 'blockquote'
}

export type Divider = {
  _type: 'divider'
  style?: 'solid' | 'dashed' | 'dotted' | 'double'
  color?: 'default' | 'primary' | 'secondary' | 'accent' | 'muted'
}

export type Callout = {
  _type: 'callout'
  type?: 'info' | 'warning' | 'error' | 'success' | 'note' | 'tip'
  title?: string
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type Code = {
  _type: 'code'
  code?: string
  language?:
    | 'javascript'
    | 'typescript'
    | 'python'
    | 'java'
    | 'cpp'
    | 'csharp'
    | 'php'
    | 'ruby'
    | 'go'
    | 'rust'
    | 'swift'
    | 'kotlin'
    | 'html'
    | 'css'
    | 'scss'
    | 'json'
    | 'yaml'
    | 'markdown'
    | 'sql'
    | 'shell'
    | 'bash'
    | 'text'
  filename?: string
  highlightedLines?: Array<number>
}

export type Youtube = {
  _type: 'youtube'
  url?: string
  title?: string
  caption?: string
}

export type Translations = {
  _id: string
  _type: 'translations'
  _createdAt: string
  _updatedAt: string
  _rev: string
  token?: string
  translation?: string
  originalText?: string
  originalLanguage?: string
  targetLanguage?: string
}

export type Footer = {
  _id: string
  _type: 'footer'
  _createdAt: string
  _updatedAt: string
  _rev: string
  copyright?: string
  socialMedia?: {
    facebook?: string
    twitter?: string
    instagram?: string
    youtube?: string
  }
  contactSection?: {
    phone?: {
      phoneNumber?: string
      phoneLink?: string
    }
    email?: {
      email?: string
      emailLink?: string
    }
    address?: {
      fullAddress?: string
      googleMapsLink?: string
      mapsEmbedLink?: string
    }
  }
}

export type Testimonial = {
  _id: string
  _type: 'testimonial'
  _createdAt: string
  _updatedAt: string
  _rev: string
  clientName?: string
  type?: 'client' | 'webinar-attendee'
  clientImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  comment?: string
  date?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type PropertyFeature = {
  _id: string
  _type: 'propertyFeature'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  type?: 'external' | 'internal'
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  description?: string
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type PropertyKind = {
  _id: string
  _type: 'propertyKind'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  main?: boolean
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  description?: string
}

export type Property = {
  _id: string
  _type: 'property'
  _createdAt: string
  _updatedAt: string
  _rev: string
  basicInfo?: {
    title?: string
    slug?: Slug
    price?: {
      currency?: 'GBP' | 'USD' | 'EUR' | 'AED' | 'TRY'
      amount?: number
    }
    images?: Array<{
      image?: {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
      }
      isCover?: boolean
      alt?: string
      _key: string
    }>
    status?: 'draft' | 'published' | 'archived' | 'sold' | 'rented' | 'on-hold'
    type?: Array<{
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'propertyKind'
    }>
    featured?: boolean
    location?: 'famagusta' | 'girne' | 'lefkosa' | 'guzelyurt' | 'iskele' | 'lefke' | 'meneou'
    listingType?: 'sale' | 'rent'
    saleType?: 'off-plan' | 'resale'
    bedrooms?: number
    livingRooms?: number
    bathrooms?: number
  }
  features?: {
    external?: Array<{
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'propertyFeature'
    }>
    internal?: Array<{
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'propertyFeature'
    }>
  }
  agent?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'propertyAgent'
  }
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  details?: {
    area?: {
      size?: number
      unit?: 'm2' | 'sqft' | 'sqkm' | 'sqmi'
    }
    yearBuilt?: number
    titleDeed?: 'exchange' | 'english' | 'turkish' | 'cyprus'
    floors?: number
    floorLevel?: number
    availableForTrade?: boolean
    gatedCommunity?: boolean
    management?: boolean
    residential?: boolean
    furnished?: boolean
    availableForViewing?: boolean
  }
}

export type PropertyAgent = {
  _id: string
  _type: 'propertyAgent'
  _createdAt: string
  _updatedAt: string
  _rev: string
  code?: string
  firstName?: string
  lastName?: string
  email?: string
  phone?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type BlogPostTag = {
  _id: string
  _type: 'blogPostTag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
}

export type UtmDestinations = {
  _id: string
  _type: 'utmDestinations'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  url?: string
  type?: 'internal' | 'external'
}

export type UtmMediums = {
  _id: string
  _type: 'utmMediums'
  _createdAt: string
  _updatedAt: string
  _rev: string
  source?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'utmSources'
  }
  medium?: string
}

export type UtmSources = {
  _id: string
  _type: 'utmSources'
  _createdAt: string
  _updatedAt: string
  _rev: string
  source?: string
}

export type Translation = {
  _id: string
  _type: 'translation'
  _createdAt: string
  _updatedAt: string
  _rev: string
  token?: string
  text?: string
  originalText?: string
  sourceLang?: string
  targetLang?: string
}

export type TranslationMetadata = {
  _id: string
  _type: 'translation.metadata'
  _createdAt: string
  _updatedAt: string
  _rev: string
  translations?: InternationalizedArrayReference
  schemaTypes?: Array<string>
}

export type InternationalizedArrayReference = Array<
  {
    _key: string
  } & InternationalizedArrayReferenceValue
>

export type InternationalizedArrayReferenceValue = {
  _type: 'internationalizedArrayReferenceValue'
  value?:
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'homePage'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'aboutPage'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'testimonialsPage'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'webinarPage'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'navigation'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'consultationPage'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'bankPackagesPage'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'blogPage'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'waitlistPage'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'faq'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'caseStudy'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'blogPost'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'privacyPolicy'
      }
}

export type PrivacyPolicy = {
  _id: string
  _type: 'privacyPolicy'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & Divider)
  >
  seo?: SeoMetaFields
  language?: string
}

export type SeoMetaFields = {
  _type: 'seoMetaFields'
  nofollowAttributes?: boolean
  metaTitle?: string
  metaDescription?: string
  metaImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  seoKeywords?: Array<string>
  openGraph?: OpenGraph
  additionalMetaTags?: Array<
    {
      _key: string
    } & MetaTag
  >
  twitter?: Twitter
}

export type BlogPost = {
  _id: string
  _type: 'blogPost'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  description?: string
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
    | ({
        _key: string
      } & Youtube)
    | ({
        _key: string
      } & Callout)
    | ({
        _key: string
      } & Divider)
    | ({
        _key: string
      } & Spacer)
    | ({
        _key: string
      } & Audio)
    | ({
        _key: string
      } & Gallery)
    | ({
        _key: string
      } & Table)
    | ({
        _key: string
      } & TextWithImage)
    | ({
        _key: string
      } & Subheading)
    | ({
        _key: string
      } & HeadingWithImage)
  >
  audio?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
    }
    media?: unknown
    _type: 'file'
  }
  readTime?: number
  author?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'team'
  }
  category?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'blogPostCategory'
  }
  tags?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'blogPostTag'
  }>
  faqs?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'faq'
  }>
  published?: boolean
  publishedAt?: string
  seo?: SeoMetaFields
  language?: string
}

export type BlogPostCategory = {
  _id: string
  _type: 'blogPostCategory'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
}

export type Team = {
  _id: string
  _type: 'team'
  _createdAt: string
  _updatedAt: string
  _rev: string
  order?: number
  name?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  role?: string
  qualification?: string
  enabled?: boolean
  leadership?: boolean
}

export type CaseStudy = {
  _id: string
  _type: 'caseStudy'
  _createdAt: string
  _updatedAt: string
  _rev: string
  clientName?: string
  slug?: string
  videoUrl?: string
  thumbnail?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  jobTitle?: string
  tagLine?: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  isFeatured?: boolean
  language?: string
}

export type Faq = {
  _id: string
  _type: 'faq'
  _createdAt: string
  _updatedAt: string
  _rev: string
  question?: string
  answer?: string
  language?: string
}

export type WaitlistPage = {
  _id: string
  _type: 'waitlistPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  seo?: SeoMetaFields
  title?: string
  subtitle?: string
  waitlistForm?: {
    form?: {
      title?: string
      firstName?: string
      lastName?: string
      email?: string
      phone?: string
      submitButton?: string
    }
  }
  publishedAt?: string
  language?: string
}

export type BlogPage = {
  _id: string
  _type: 'blogPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  subtitle?: string
  featuredPosts?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'blogPost'
  }>
  seo?: SeoMetaFields
  language?: string
}

export type BankPackagesPage = {
  _id: string
  _type: 'bankPackagesPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  seo?: SeoMetaFields
  title?: string
  subtitle?: string
  packages?: Array<{
    title?: string
    icon?: string
    subtitle?: string
    slug?: string
    stripePriceId?: string
    minimumDeposit?: number
    buttonText?: string
    moreText?: string
    description?: string
    price?: number
    features?: Array<{
      title?: string
      _key: string
    }>
    _key: string
  }>
  form?: {
    title?: string
    personalInformationSection?: {
      title?: string
      salutation?: string
      firstName?: string
      lastName?: string
      email?: string
      phone?: string
    }
    additionalInformationSection?: {
      title?: string
      dateOfBirth?: string
      placeOfBirth?: string
      address?: string
      city?: string
      country?: string
      zipCode?: string
      maritalStatus?: string
      profession?: string
    }
    parentsInformationSection?: {
      title?: string
      fathersFirstName?: string
      fathersLastName?: string
      mothersFirstName?: string
      mothersLastName?: string
      mothersMaidenName?: string
    }
    bankAndLawyerSection?: {
      title?: string
      bankAppointment?: string
      initialDeposit?: string
      amountToBeTransferred?: string
      lawyerAppointment?: string
      travelDetails?: {
        title?: string
        areYouTravellingAlone?: string
        numberOfPeople?: string
        whoIsTravellingWithYou?: string
        numberOfChildren?: string
        comments?: string
        doYouNeed?: string
        arrivalDate?: string
        departureDate?: string
        hotel?: string
        requireRentalCar?: string
        carSize?: string
      }
      additionalServices?: {
        title?: string
        airportTransfer?: string
      }
    }
    documentUploadsSection?: {
      title?: string
      mainTravellerDocuments?: {
        title?: string
        passport?: string
        utilityBill?: string
        idFront?: string
        idBack?: string
        proofOfTravel?: string
      }
      additionalTravellerDocuments?: {
        title?: string
        additionalTravellerRadios?: {
          title?: string
          passport?: string
          id?: string
        }
        passport?: string
        idFront?: string
        idBack?: string
        proofOfTravel?: string
      }
    }
    buttons?: {
      back?: string
      next?: string
      submit?: string
    }
  }
  publishedAt?: string
  language?: string
}

export type ConsultationPage = {
  _id: string
  _type: 'consultationPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  subtitle?: string
  offerInformation?: {
    label?: string
    items?: Array<{
      icon?: string
      title?: string
      _key: string
    }>
  }
  closerInformation?: {
    title?: string
    subtitle?: string
  }
  form?: {
    title?: string
    subtitle?: string
  }
  publishedAt?: string
  language?: string
  seo?: SeoMetaFields
}

export type Navigation = {
  _id: string
  _type: 'navigation'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  items?: Array<{
    name?: string
    href?: string
    hideOnHomePage?: boolean
    hidden?: boolean
    children?: Array<{
      name?: string
      href?: string
      hidden?: boolean
      _key: string
    }>
    _key: string
  }>
  bookCall?: {
    title?: string
    href?: string
    hidden?: boolean
  }
  language?: string
}

export type WebinarPage = {
  _id: string
  _type: 'webinarPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  seo?: SeoMetaFields
  title?: string
  subtitle?: string
  CTA?: {
    label?: string
    url?: string
  }
  webinarInformationSection?: {
    date?: string
    timezone?: string
  }
  benefitsSection?: {
    title?: string
    benefits?: Array<{
      title?: string
      description?: string
      _key: string
    }>
    CTA?: {
      label?: string
      url?: string
    }
  }
  aboutHostSection?: {
    title?: string
    subTitle?: string
    paragraph1?: string
    paragraph2?: string
  }
  statisticsSection?: Array<{
    prefix?: string
    number?: number
    postfix?: string
    description?: string
    _key: string
  }>
  registrationSection?: {
    form?: {
      title?: string
      firstName?: string
      lastName?: string
      email?: string
      phone?: string
      submitButton?: string
    }
    webinarFeatures?: Array<{
      icon?: string
      title?: string
      _key: string
    }>
  }
  publishedAt?: string
  language?: string
}

export type TestimonialsPage = {
  _id: string
  _type: 'testimonialsPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  seo?: SeoMetaFields
  name?: string
  title?: string
  description?: string
  CTA?: {
    label?: string
    url?: string
  }
  publishedAt?: string
  language?: string
}

export type AboutPage = {
  _id: string
  _type: 'aboutPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  seo?: SeoMetaFields
  title?: string
  subtitle?: string
  missionVisionSection?: {
    mission?: {
      title?: string
      content?: string
    }
    vision?: {
      title?: string
      content?: string
    }
    CTA?: {
      label?: string
      url?: string
    }
  }
  aboutRabihSection?: {
    title?: string
    subTitle?: string
    paragraph1?: string
    paragraph2?: string
    cta?: {
      label?: string
      url?: string
    }
  }
  testimonialsSection?: {
    title?: string
    CTA?: {
      label?: string
      url?: string
    }
  }
  gallerySection?: {
    title?: string
    description?: string
  }
  callToActionSection?: {
    title?: string
    description?: string
    CTA?: {
      label?: string
      url?: string
    }
  }
  publishedAt?: string
  language?: string
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  seo?: SeoMetaFields
  title?: string
  subtitle?: string
  buttons?: Array<{
    label?: string
    url?: string
    _key: string
  }>
  whyUsSection?: {
    title?: string
    description?: string
    reasons?: Array<{
      title?: string
      description?: string
      _key: string
    }>
  }
  aboutSection?: {
    title?: string
    description?: string
    paragraphs?: Array<string>
    CTA?: {
      label?: string
      url?: string
    }
  }
  testimonialsSection?: {
    title?: string
    CTA?: {
      label?: string
      url?: string
    }
  }
  partnersSection?: {
    title?: string
  }
  consultationProcessSection?: {
    title?: string
    description?: string
    steps?: Array<{
      icon?: string
      title?: string
      subtitle?: string
      description?: string
      _key: string
    }>
    CTA?: {
      label?: string
      url?: string
    }
  }
  whyCyprusSection?: {
    title?: string
    reasons?: Array<{
      title?: string
      description?: string
      _key: string
    }>
    CTA?: {
      label?: string
      url?: string
    }
  }
  caseStudiesSection?: {
    title?: string
    description?: string
  }
  investorCommunitySection?: {
    CTA?: {
      label?: string
      url?: string
    }
  }
  meetRabihSection?: {
    title?: string
    subTitle?: string
    paragraph1?: string
    paragraph2?: string
    CTA?: {
      label?: string
      url?: string
    }
  }
  leadershipTeamSection?: {
    title?: string
    description?: string
  }
  callToActionSection?: {
    title?: string
    description?: string
    CTA?: {
      label?: string
      url?: string
    }
  }
  freebieSignupSection?: {
    title?: string
    description?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    consent?: string
    form?: {
      firstName?: string
      lastName?: string
      email?: string
      submit?: string
    }
  }
  publishedAt?: string
  language?: string
}

export type Twitter = {
  _type: 'twitter'
  cardType?: string
  creator?: string
  site?: string
  handle?: string
}

export type OpenGraph = {
  _type: 'openGraph'
  url?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  title?: string
  description?: string
  siteName?: string
}

export type MetaTag = {
  _type: 'metaTag'
  metaAttributes?: Array<
    {
      _key: string
    } & MetaAttribute
  >
}

export type MetaAttribute = {
  _type: 'metaAttribute'
  attributeKey?: string
  attributeType?: 'string' | 'image'
  attributeValueImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  attributeValueString?: string
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | TextWithImage
  | Table
  | Spacer
  | Subheading
  | HeadingWithImage
  | Gallery
  | Audio
  | Quote
  | Divider
  | Callout
  | Code
  | Youtube
  | Translations
  | Footer
  | Testimonial
  | SanityImageCrop
  | SanityImageHotspot
  | PropertyFeature
  | Slug
  | PropertyKind
  | Property
  | PropertyAgent
  | BlogPostTag
  | UtmDestinations
  | UtmMediums
  | UtmSources
  | Translation
  | TranslationMetadata
  | InternationalizedArrayReference
  | InternationalizedArrayReferenceValue
  | PrivacyPolicy
  | SeoMetaFields
  | BlogPost
  | BlogPostCategory
  | Team
  | CaseStudy
  | Faq
  | WaitlistPage
  | BlogPage
  | BankPackagesPage
  | ConsultationPage
  | Navigation
  | WebinarPage
  | TestimonialsPage
  | AboutPage
  | HomePage
  | Twitter
  | OpenGraph
  | MetaTag
  | MetaAttribute
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
export declare const internalGroqTypeReferenceTo: unique symbol
